Features/chapter1
voldem007/SimpleRss pull request #1
Opened 2018-11-19 08:55 UTC by voldem007

2018-11-19 12:11 UTC, warokku reviewed
1. Please consider [this](https://docs.swift.org/swift-book/LanguageGuide/Extensions.html) language feature instead of declaring internal classes for using as Delegates and DataSources.
2. 1 source file == 1 class (with some extensions/nested classes/structs/protocol declarations).
3. [Working with optionals](https://cocoacasts.com/swift-fundamentals-working-with-optionals).
4. From task's description: "Cell layout should be implemented via Auto-Layout to support device orientation changes."

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/Models/Topic.swift
> +    init(id: Int, title: String, url: String) {
Swift automatically generates constructors initializing all variable for structs.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +        self.view.addSubview(tableView!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: (self.context?.feedCellIdentifier)!)! as! FeedViewCell
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +            let data = try? Data(contentsOf: url!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +                cell.imageView?.image = UIImage(data: data!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        self.view.addSubview(tableView!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        return (context?.topics.count)!
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: (self.context?.topicCellIdentifier)!)! as! TopicViewCell
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        let url = URL(string: (self.context?.topics[indexPath.row].url)!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +            let data = try? Data(contentsOf: url!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +                cell.PreviewImageView.image = UIImage(data: data!)
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to use this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/TopicViewCell.swift
> +    @IBOutlet var PreviewImageView: UIImageView!
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to declare this variable.

Also, [please follow these naming conventions](https://swift.org/documentation/api-design-guidelines/#naming)

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/TopicViewCell.swift
> +    @IBOutlet var TitleLabel: UILabel!
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to declare this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +    var name: String!
Use of force unwrapping is strongly discouraged in Swift projects. Please find another way to declare this variable.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +        cell.titleLabel.text = "Title"
Constants are usually declared as static variables, sometimes nested in internal struct named "Constants":
```
public class SomeClass {
    private struct Constants {
        static let cellTitle = "Title"
    }

    func someFunc() {
        someCell.titleLabel.text = Constants.cellTitle
    }
}
```
Same technique is used for urls and numbers.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +                                 Topic(id: 2, title: "Politics", url: "https://img.tyt.by/n/it/0f/7/world-of-tanks.jpg")]
What is the purpose of Topic.id field?

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        tableView?.rowHeight = UITableView.automaticDimension
The default value of rowHeight is automaticDimension.

2018-11-19 12:11 UTC, warokku commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        context?.navigationController?.pushViewController(FeedViewController(name: indexPath.row), animated: true)
I think here Topics delegate class depends on context **having** navigation controller to work properly, and I also think this is the case where should take [DIP](https://en.wikipedia.org/wiki/Dependency_inversion_principle) and [Open-Closed principle into consideration](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle)

2018-11-19 12:32 UTC, Viktor-by commented on SimpleRss/SimpleRss/Models/Topic.swift
> +    init(id: Int, title: String, url: String) {
1

2018-11-20 06:03 UTC, Viktor-by commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +    weak var context: HomeViewController?
It is not necessary to create such dependency to HomeViewController in datasource.

Create a property for topics, update initializer and use topics value in datasource methods.

`let topics: [Topic]`

2018-11-20 06:03 UTC, Viktor-by commented on SimpleRss/SimpleRss/ViewControllers/TopicViewCell.swift
> +    @IBOutlet var TitleLabel: UILabel!
I think it's acceptable for IBOutlets

2018-11-20 06:03 UTC, Viktor-by commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +    let topicCellIdentifier = "TopicViewCell"
Create an extension for UITableViewCell with a function "cellIdentifier" returning a class name. Use this method instead of "topicCellIdentifier" and "feedCellIdentifier" (e.g. TopicViewCell.cellIdentifier)

2018-11-22 06:42 UTC, Viktor-by requested changes

2018-11-22 06:42 UTC, Viktor-by commented on SimpleRss/SimpleRss/Services/XMLParserService.swift
> +        if foundElementName == "title" {
`guard let` would be very helpful in such cases, when a method has no sense without a valid variable.

2018-11-22 06:42 UTC, Viktor-by commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +    var url: String!
Please avoid implicitly unwrapping here and in the init below.

2018-11-22 06:42 UTC, Viktor-by commented on SimpleRss/SimpleRss/Services/XMLParserService.swift
> +        parser = XMLParser(contentsOf: URL(string: url)!)!
Add 'guard let' for URL and XMLParser

2018-11-22 06:42 UTC, Viktor-by commented on SimpleRss/SimpleRss/ViewControllers/HomeViewController.swift
> +        cell.PreviewImageView?.downloaded(from: topics[indexPath.row].picUrl)
As I can see 'TitleLabel' and 'PreviewImageView' is already implicitly unwrapped. No need for optional chaining.

2018-11-22 06:42 UTC, Viktor-by commented on SimpleRss/SimpleRss/Views/FeedViewCell.swift
> +    @IBOutlet weak var PreviewImageView: UIImageView!
Please rename :)
All variables, properties and methods start with lowercased letter.

2018-11-22 06:42 UTC, Viktor-by commented on SimpleRss/SimpleRss/ViewControllers/FeedViewController.swift
> +        cell.DescriptionLabel.numberOfLines = cell.DescriptionLabel.numberOfLines == 0 ? 1 : 0;
Please, try the following case:
Open a feed, tap the first cell, scroll the table view.
How many expanded cell do you see?

2018-11-23 09:23 UTC, merged