Features/chapter4
voldem007/SimpleRss pull request #4
Opened 2019-01-05 22:23 UTC by voldem007

2019-01-15 08:06 UTC, Viktor-by requested changes

2019-01-15 08:06 UTC, Viktor-by commented on SimpleRss/SimpleRss/Views/FeedViewCell.swift
> +            ImageDownloadOrchestrator.shared.cancel(getOperation)
Cancel operation in prepareForReuse. Same for TopicViewCell

2019-01-15 08:06 UTC, Viktor-by commented on SimpleRss/SimpleRss/Services/ImageDownloadOrchestrator.swift
> +        let getOp = cacheManager.get(url: url)
Why not to check if file exists on the disk before that?

2019-01-15 08:06 UTC, Viktor-by commented on SimpleRss/SimpleRss/Views/Operations/DownloadImageOperation.swift
> +        if isCancelled {
This chunk of code would make sense if you were using NSURLSession and could cancel dowloading operation. Same for GetImageOperation

2019-01-15 08:06 UTC, Viktor-by commented on SimpleRss/SimpleRss/Services/ImageDownloadOrchestrator.swift
> +            if !getOp.isCancelled {
Move that check to `guard let`

2019-01-15 10:38 UTC, voldem007 commented on SimpleRss/SimpleRss/Services/ImageDownloadOrchestrator.swift
> +        let getOp = cacheManager.get(url: url)
insert check for exist into getOperation

2019-01-17 05:41 UTC, warokku approved these changes

2019-01-17 05:41 UTC, warokku commented on SimpleRss/SimpleRss/Views/TopicViewCell.swift
> +            let getOp = GetImageOperation((imageUrl?.lastPathComponent)!)
Please remove force unwrapping here

2019-01-17 05:41 UTC, warokku commented on SimpleRss/SimpleRss/Views/TopicViewCell.swift
> +            let downloadOp = DownloadImageOperation(imageUrl!)
And here

2019-01-17 06:06 UTC, Viktor-by approved these changes

2019-01-17 06:42 UTC, voldem007 commented on SimpleRss/SimpleRss/Views/TopicViewCell.swift
> +            let downloadOp = DownloadImageOperation(imageUrl!)
looks like previous changes, won't fix

2019-01-17 06:42 UTC, voldem007 commented on SimpleRss/SimpleRss/Views/TopicViewCell.swift
> +            let getOp = GetImageOperation((imageUrl?.lastPathComponent)!)
looks like previous changes, won't fix

2019-01-17 07:01 UTC, merged